#!/usr/bin/env sh
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Bash sanity settings (error on exit, complain for undefined vars, error when pipe fails)
set -euo

. /etc/os-release

if [ "${ID}" = "debian" ]; then
    echo
    echo "Installing packages for Debian:" "$@"
    echo
    apt-get update \
    && apt-get install -y --no-install-recommends \
           "$@" \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
elif [ "${ID}" = "alpine" ]; then
    echo
    echo "Installing packages for Alpine:" "$@"
    echo
    apk add --no-cache --virtual .build-deps "$@"
else
    echo
    echo "Exiting. The os ${ID} is unknown."
    echo
    exit 1
fi
