#!/usr/bin/env sh
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -eu

. /etc/os-release

if [ "${ID}" = "debian" ]; then
    echo
    echo "Preparing Debian image"
    echo
    /root/install_packages curl gnupg2
    curl -sL https://deb.nodesource.com/setup_10.x | bash -

elif [ "${ID}" = "alpine" ]; then
    echo
    echo "Preparing Alpine image"
    echo
    echo @edge-community http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
      && echo @edge-testing http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories \
      && echo @edge http://dl-cdn.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories
    apk update
    /root/install_packages bash
else
    echo
    echo "Exiting. The os ${ID} is unknown."
    echo
    exit 1
fi
