---
name: Airflow Security Issue
description: Security issues of Airflow
labels: ["needs triage"]
body:
  - type: textarea
    attributes:
      label: The issue description
      description: Description of the security issue copied from the original report
      placeholder: >
        Please provide the content of the original report of the security issue 
        from the `security@airflow.apache.org` mailing list
    validations:
      required: true
  - type: input
    attributes:
      label: Security mailing list thread
      description: >
        Type in the link to the 
        [thread in the security mailing list](https://lists.apache.org/list.html?security@airflow.apache.org)
      placeholder: "Please paste the link to the discussion in the security@airlfow.apache.org mailing list"
    validations:
      required: true
  - type: input
    attributes:
      label: Reporter credited as
      description: How reporter should be credited
      placeholder: "Type in the reporter name as it should be credited in the announcement"
    validations:
      required: false
  - type: input
    attributes:
      label: PR with the fix
      description: >
          Proposed PR with the fix in the [Airflow repository](https://github.com/apache/airflow)
      placeholder: "When we have the PR to fix the issue we should link it here"
    validations:
      required: false
  - type: input
    attributes:
      label: CWE
      description: CWE (Common Weakness Enumeration) number [from the CWE list](https://cwe.mitre.org/data/index.html)
      placeholder: "We should add CWE number here"
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Severity
      description: >
        What is the initial severity you think should be applied (we can change it later - pick Unknown if unsure).
        The criteria to assess the severity are described in the
        [Severity Rating blog post](https://security.apache.org/blog/severityrating)
      multiple: false
      options:
        - "Critical"
        - "Important"
        - "Moderate"
        - "Low"
        - "Unknown"
    validations:
      required: true
  - type: input
    attributes:
      label: CVE tool link
      description: Link to [the CVE tool](https://cveprocess.apache.org/allocatecve) entry
      placeholder: "When we request the CVE number we should link it here"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Please attach any files that were received with the report!"
