#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This is hook build used by DockerHub. We are also using it
# on Travis CI to potentially rebuild (and refresh layers that
# are not cached) Docker images that are used to run CI jobs

set -euo pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "My dir: ${MY_DIR}"

AIRFLOW_SOURCES="$(cd "${MY_DIR}/.." && pwd)"
export AIRFLOW_SOURCES

# shellcheck source=scripts/ci/utils/_init.sh
. "${MY_DIR}/../scripts/utils/_init.sh"
# shellcheck source=scripts/ci/utils/_build.sh
. "${MY_DIR}/../scripts/utils/_build.sh"

script_start

initialize_environment

prepare_build

rebuild_ci_image_if_needed
rebuild_ci_slim_image_if_needed
rebuild_checklicence_image_if_needed
rebuild_prod_image_if_needed

push_ci_image
push_ci_slim_image
push_prod_image
